Future<List<Map<dynamic, dynamic>>> fetchInitialEntries() async {  // Load first profiles from firebase user database

  await Future.delayed(Duration(seconds: 2));
  
  List<Map<dynamic, dynamic>> profileData = [  // Replace with actual database call
  {'profilePic':'assets/test_photos/IMG_0197.jpeg', 
    'images':
    ['assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg',
    ], 
    'name':'Elijah', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'1 mi'}, 
  {'profilePic':'assets/test_photos/IMG_0164.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'10 mi'}, 
  {'profilePic':'assets/test_photos/IMG_0310.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'1 mi'},
  {'profilePic':'assets/test_photos/IMG_0197.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'1 mi'}, 
  {'profilePic':'assets/test_photos/IMG_0164.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'10 mi'}, 
  {'profilePic':'assets/test_photos/IMG_0310.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'1 mi'},
  {'profilePic':'assets/test_photos/IMG_0197.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'1 mi'}, 
  {'profilePic':'assets/test_photos/IMG_0164.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'10 mi'}, 
  {'profilePic':'assets/test_photos/IMG_0310.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'1 mi'},
  {'profilePic':'assets/test_photos/IMG_0197.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'1 mi'}, 
  {'profilePic':'assets/test_photos/IMG_0164.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'10 mi'}, 
  {'profilePic':'assets/test_photos/IMG_0310.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'1 mi'},
  {'profilePic':'assets/test_photos/IMG_0197.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'1 mi'}, 
  {'profilePic':'assets/test_photos/IMG_0164.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'10 mi'}, 
  {'profilePic':'assets/test_photos/IMG_0310.jpeg', 
    'images':[
    'assets/test_photos/IMG_0164.jpeg', 
    'assets/test_photos/IMG_0167.jpeg', 
    'assets/test_photos/IMG_0168.jpeg', 
    'assets/test_photos/IMG_0197.jpeg',
    'assets/test_photos/IMG_0206.jpeg', 
    ],
    'name':'Elijah Medrano', 
    'age':'24', 
    'height':'5\'10"', 
    'location':'Euless, TX', 
    'distance':'1 mi'}];

  return profileData;
}